### ISSUE TITLE
Examples in Arduino IDE 2.0 not opening correctly

### ISSUE THREAD

**Issue by patryksew** [arduino-libraries/Servo#100]
When I try to open an example from Servo library, readme opens. It does not happen with other libraries.

**Comment by per1234** [comment]
Hi @patryksew. Thanks for your report.

Since this is not anything specific to the Servo library (it happens for any sketch that contains a file supported for opening in the Arduino IDE), I will close it as off topic for the Servo library repository.

Please open the issue in the Arduino IDE repository here:

https://github.com/arduino/arduino-ide/issues/new/choose

I think it will provide valuable feedback about this new behavior of the Arduino IDE 2.x
