### ISSUE TITLE
Online simulator pages for Servo Library - New feature 😀

### ISSUE THREAD

**Issue by matititam** [arduino-libraries/Servo#62]
Hi there

Thank you very much for the most used and working library. We have been working on an Arduino simulator for the Arduino community ♥. It is free to use for all and needs no login or additional downloads. It runs right out of the browser.

We have created online simulation pages and we will be glad to create a PR to add the information about the simulation pages in the ReadMe file. I believe it will be interesting for the users of the library as well. Kindly give your kind feedback 😀

https://wokwi.com/arduino/libraries/Servo 

you can find the simulations running in the below link
🙏

Best Regards
Puneeth

**Comment by per1234** [comment]
Hi @matititam. Thanks for sharing, and for your work on Wowki. This is a valuable resource for the Arduino community.

Since the lack of any activity on this issue after 1.5 years clearly shows that those authorized to make such decisions are not participating in the maintenance of this project, I don't think it will be feasible to accept your generous proposal for enhancing the documentation.
